#Requires -Version 7
<#
.SYNOPSIS
    Generates the per-layer documentation indexes (docs/index.md and docs-functional/index.md).

.DESCRIPTION
    Each documentation layer keeps a catalog the agent reads before answering or editing, so it
    finds the right page instead of spawning duplicates or orphans (see docs/ai-sdlc/docs-wiki.md).
    This generator emits those catalogs deterministically from the markdown pages in each layer, so
    the index cannot drift from reality:

      - One entry per page: a relative markdown link plus a one-sentence summary.
      - Entries grouped by area: the immediate subfolder under the layer (e.g. adrs, conventions,
        handlers, libraries, ai-sdlc). Top-level pages go under "General".
      - Title comes from the page's first H1; the summary is the first prose line after it, skipping
        front-matter, bold metadata lines, blockquote notes, and headings. If no prose is derivable
        the title is reused; if there is no H1 either, the filename is used. No summary is invented.
      - The index files themselves and obvious templates (0000-template.md) are excluded.
      - Groups and entries are sorted alphabetically so regeneration is byte-stable. The file carries
        a generated-file header and no timestamp, so -Check can compare committed against generated.

    Default (no switch): writes the indexes. -Check: writes nothing, compares each committed index to
    what would be generated now, prints any out of sync and exits 1; prints OK and exits 0 if in sync.
    This is the index-drift gate. Missing layer folders are skipped with a note.

.PARAMETER RepoRoot
    Repository root containing docs/ and docs-functional/. Defaults to two levels above this script.

.PARAMETER Check
    Compare committed indexes against freshly generated content instead of writing. Exits non-zero
    if any index is out of date.
#>
[CmdletBinding()]
param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..' '..')).Path,
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$layers = @('docs', 'docs-functional')
$indexFileName = 'index.md'
$excludedNames = @('index.md', '0000-template.md')
$generatedHeader = 'Generated by MindNova/tools/Build-DocsIndex.ps1; do not edit by hand. Run the script to regenerate.'
$generalGroup = 'General'
$maxSummaryLength = 200

function Get-PageTitle([string[]]$lines) {
    foreach ($line in $lines) {
        $m = [regex]::Match($line, '^\s*#\s+(.+?)\s*$')
        if ($m.Success) { return $m.Groups[1].Value.Trim() }
    }
    return $null
}

function Get-PageSummary([string]$text) {
    $body = [regex]::Replace($text, '\A\s*---\r?\n.*?\r?\n---\r?\n', '', 'Singleline')
    foreach ($raw in ($body -split '\r?\n')) {
        $line = $raw.Trim()
        if ($line -eq '') { continue }
        if ($line -match '^#{1,6}\s') { continue }              # markdown heading
        if ($line -match '^>') { continue }                     # blockquote note
        if ($line -match '^(\*\*[^*]+:\*\*|__[^_]+:__)') { continue }     # bold metadata label (e.g. **Status:** Accepted)
        if ($line -match '^[-*+]\s' -or $line -match '^\d+\.\s') { $line = ($line -replace '^([-*+]|\d+\.)\s+', '') }
        if ($line -match '^[`|]') { continue }                  # code fence or table row
        $sentence = [regex]::Match($line, '^(.*?[.!?])(\s|$)')
        $summary = if ($sentence.Success) { $sentence.Groups[1].Value.Trim() } else { $line }
        $summary = ($summary -replace '\s+', ' ').Trim()
        if ($summary.Length -gt $maxSummaryLength) {
            $summary = $summary.Substring(0, $maxSummaryLength).TrimEnd() + '...'
        }
        if ($summary -ne '') { return $summary }
    }
    return $null
}

function Sanitize([string]$value) {
    if (-not $value) { return $value }
    return ($value -replace [char]0x2014, ' - ').Trim()
}

function Get-LayerEntries([string]$layerPath, [string]$layerName) {
    $pages = Get-ChildItem -Path $layerPath -Recurse -Include *.md, *.markdown -File |
        Where-Object { $excludedNames -notcontains $_.Name }

    $entries = [System.Collections.Generic.List[object]]::new()
    foreach ($page in $pages) {
        $text = Get-Content -LiteralPath $page.FullName -Raw
        $lines = $text -split '\r?\n'

        $title = Get-PageTitle $lines
        $summary = Get-PageSummary $text

        if (-not $title) { $title = $page.BaseName }
        if (-not $summary) { $summary = $title }

        $relFromLayer = [IO.Path]::GetRelativePath($layerPath, $page.FullName).Replace('\', '/')
        $linkPath = './' + $relFromLayer

        $dirRel = [IO.Path]::GetRelativePath($layerPath, $page.Directory.FullName).Replace('\', '/')
        $group = if ($dirRel -eq '.') { $generalGroup } else { ($dirRel -split '/')[0] }

        $entries.Add([pscustomobject]@{
                Group   = $group
                Title   = (Sanitize $title)
                Link    = $linkPath
                Summary = (Sanitize $summary)
                SortKey = $linkPath
            })
    }
    return $entries
}

function Build-IndexContent([System.Collections.Generic.List[object]]$entries, [string]$layerName) {
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("# $layerName index")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("<!-- $generatedHeader -->")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('One entry per page (relative link plus a one-sentence summary), grouped by area.')

    $groups = $entries | Group-Object Group | Sort-Object Name
    foreach ($g in $groups) {
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("## $($g.Name)")
        [void]$sb.AppendLine()
        foreach ($e in ($g.Group | Sort-Object SortKey)) {
            [void]$sb.AppendLine("- [$($e.Title)]($($e.Link)) - $($e.Summary)")
        }
    }
    return ($sb.ToString().TrimEnd("`r", "`n") + "`n")
}

$anyDrift = $false
$processedLayers = 0

foreach ($layerName in $layers) {
    $layerPath = Join-Path $RepoRoot $layerName
    if (-not (Test-Path $layerPath)) {
        Write-Host "Skipping '$layerName': layer folder not found at $layerPath."
        continue
    }
    $processedLayers++

    $entries = Get-LayerEntries $layerPath $layerName
    $content = Build-IndexContent $entries $layerName
    $indexPath = Join-Path $layerPath $indexFileName
    $relIndex = [IO.Path]::GetRelativePath($RepoRoot, $indexPath).Replace('\', '/')

    if ($Check) {
        if (-not (Test-Path $indexPath)) {
            Write-Host "  DRIFT: $relIndex is missing; run Build-DocsIndex.ps1 to generate it." -ForegroundColor Red
            $anyDrift = $true
            continue
        }
        $current = (Get-Content -LiteralPath $indexPath -Raw) -replace "`r`n", "`n"
        $expected = $content -replace "`r`n", "`n"
        if ($current -ne $expected) {
            Write-Host "  DRIFT: $relIndex is out of date; run Build-DocsIndex.ps1 to regenerate." -ForegroundColor Red
            $anyDrift = $true
        }
    }
    else {
        Set-Content -LiteralPath $indexPath -Value $content -NoNewline -Encoding utf8
        Write-Host ("Wrote {0} ({1} page(s))." -f $relIndex, $entries.Count)
    }
}

if ($Check) {
    if ($anyDrift) {
        Write-Host 'Docs index drift detected; regenerate with Build-DocsIndex.ps1.' -ForegroundColor Red
        exit 1
    }
    Write-Host ("Docs index OK: {0} layer index file(s) in sync." -f $processedLayers)
    exit 0
}

Write-Host ("Done: generated {0} layer index file(s)." -f $processedLayers)
exit 0
